### ISSUE TITLE
Unsupported Media Type

### ISSUE THREAD

**Issue by ghost** [h2non/node-imaginary#5]
Hi!

I've been using this library with the imaginary server and for some images I get "415 Unsupported Media Type". If I make the call directly to the imaginary server everything works just fine.

If you want to test this behavior:
- imaginary server url: https://images.balloonas.com
- image url: https://s3.eu-central-1.amazonaws.com/dev.balloonas.images/gifts/birthday-gift/Süße-Sorgenfresser-Schlüsselanhänger-238656107506.jpg
- call that is made to node.js server: https://dev.balloonas.org/images/gifts/birthday-gift/SüßeSorgenfresser-Schlüsselanhänger/238656107506?size=600x600

**Comment by h2non** [comment]
This is due the `Content-Type` header is not properly defined in the request or the payload was bad formed. Try passing the URL of the image as param:

``` js
const url = 'https://s3.eu-central-1.amazonaws.com/dev.balloonas.images/gifts/birthday-gift/Süße-Sorgenfresser-Schlüsselanhänger-238656107506.jpg'

imaginary(url)
  .server('https://images.balloonas.com')
  .crop({ width: 100, url: url })
  .on('error', function (err) {
    console.error('Cannot resize the image:', err)
  })
  .pipe(fs.createWriteStream('out.jpg'))
```

I've tried using the URL and it works:
https://images.balloonas.com/crop?width=100&url=https://s3.eu-central-1.amazonaws.com/dev.balloonas.images/gifts/birthday-gift/S%C3%BC%C3%9Fe-Sorgenfresser-Schl%C3%BCsselanh%C3%A4nger-238656107506.jpg

**Comment by h2non** [comment]
@marinsicavirdol I'm working on this. Will release a fresh version with the fix very soon.

**Comment by h2non** [comment]
The image you're using seems to be corrupted. It cannot be recognized by the algorithm used in Go to inter the MIME type of the first 512 bytes (effectively, the magic number file signature).

The code is failing here: https://github.com/h2non/imaginary/blob/master/controllers.go#L51
Due to this implementation: https://golang.org/src/net/http/sniff.go?s=648:690#L11
Which follows the algorithm specification from: https://mimesniff.spec.whatwg.org/

My opinion is that the algorithm supported natively in Go is not versatile enough to infer all kind magic number bytes, so I would consider using another implementation, such as [this one](https://github.com/h2non/filetype) I wrote a time ago.

Just to clarify, the node client is fine.

**Comment by h2non** [comment]
Your image has the proper magic number signature as JPEG image. The issue is in the `stdlib` of Go programming language. I'll report this issue to the Go team. 

By the way, I'm going to update `imaginary` supporting an additional level of image type inference checking the magic numbers signature. This should solve your problem. I'll let you know when it's ready.

**Comment by ghost** [comment]
@h2non this URL: https://images.balloonas.com/crop?width=100&url=https://s3.eu-central-1.amazonaws.com/dev.balloonas.images/gifts/birthday-gift/S%C3%BC%C3%9Fe-Sorgenfresser-Schl%C3%BCsselanh%C3%A4nger-238656107506.jpg and this URL: https://dev.balloonas.org/images/gifts/birthday-gift/SüßeSorgenfresser-Schlüsselanhänger/238656107506?size=600x600 - should give back the image https://s3.eu-central-1.amazonaws.com/dev.balloonas.images/gifts/birthday-gift/Süße-Sorgenfresser-Schlüsselanhänger-238656107506.jpg

So the Go server can process the image using direct URL (first link) but it can't using the node client(second link). This means that the Go implementation is fine, right?

**Comment by h2non** [comment]
This only applies when image type is inferred reading the HTTP request payload. The process for processing images from URLs doesn't perform this check in that way.

I'm going to fix it `imaginary`.

**Comment by h2non** [comment]
Issue moved here: https://github.com/h2non/imaginary/issues/79

**Comment by h2non** [comment]
Here it's the real problem. S3 is returning an XML as response when requesting the image from `node.js`:

``` xml
<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>EB05CF1EA3D9FAF1</RequestId><HostId>YDzQ7t/KRNSXyZ99soossjrODLL+P34kH64KDLDRc31J+Qokcou3JkpSs2oYp7KUFE2TolizWbA=</HostId></Error>
```

Seems like the S3 bucket has some sort access policy based on the `User-Agent` header or something.

**Comment by ghost** [comment]
This is really strange as it happens only on some images and these images are in the same bucket with the same access policy.

**Comment by ghost** [comment]
Ok, you were right! I've changed the value of the url passed to node client with a signed url from s3. Thank you very much for the help.
