### ISSUE TITLE
Update to ES6 class syntax

### ISSUE THREAD

**Issue by krazyjakee** [h2non/node-imaginary#8]
How do you feel about this?

It would certainly improve readability.

**Comment by h2non** [comment]
Absolutely! Especially now since recent node.js supports almost the full ES6 language syntax (however, I want to provide support for old node.js versions too, so a transpiler must be used).

Refactoring it is just a matter of time and priorities. If you are genuinely interested, I will accept any PR that introduces any enhancement in this sense.

**Comment by krazyjakee** [comment]
My latest pull request concludes the best start for the es6 update. I will open new issues for any other enhancements we can now do (promises etc).

**Comment by h2non** [comment]
Done!
